# Requires cocoaPods 0.36.0.beta.2 or better.

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TGPControlsDemo' do
    #pod 'TGPControls', :path => '../../TGPControls'
    pod 'TGPControls'
end

target 'TGPControlsDemoTests' do

end

