# Requires cocoaPods 0.36.0.beta.2 or better.
# To update use: `gem install cocoapods --pre`

platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TGPControlsDemo' do
    # pod 'TGPControls', :path => '../../TGPControls'
    pod 'TGPControls', '0.0.2'
end

target 'TGPControlsDemoTests' do

end

