platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TGPControlsDemo7' do
    #pod 'TGPControls', :path => '../../TGPControls'
    pod 'TGPControls'
end

target 'TGPControlsDemo7Tests' do

end

