platform :ios, '7.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'TGPControlsDemo7' do
    # pod 'TGPControls', :path => '../../TGPControls'
    pod 'TGPControls', '0.0.2'
end

target 'TGPControlsDemo7Tests' do

end

